bank_app/urls.py
from django.urls import path
from . import views


app_name = "bank_app"

urlpatterns = [
  path('', views.index, name='index'),

    path('dashboard/', views.dashboard, name='dashboard'),
    path('account_details/<int:pk>/', views.account_details, name='account_details'),
    path('card_list/', views.card_list, name='card_list'),
    path('transaction_details/<int:transaction>/', views.transaction_details, name='transaction_details'),
    path('make_transfer/', views.make_transfer, name='make_transfer'),
    path('make_loan/', views.make_loan, name='make_loan'),

    path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('staff_search_partial/', views.staff_search_partial, name='staff_search_partial'),
    path('staff_customer_details/<int:pk>/', views.staff_customer_details, name='staff_customer_details'),
    path('staff_account_list_partial/<int:pk>/', views.staff_account_list_partial, name='staff_account_list_partial'),
    path('staff_account_details/<int:pk>/', views.staff_account_details, name='staff_account_details'),
    path('staff_new_account_partial/<int:user>/', views.staff_new_account_partial, name='staff_new_account_partial'),
    path('staff_new_customer/', views.staff_new_customer, name='staff_new_customer'),

]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(tf_urls)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('bank_app.urls')),
   
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">

    <title>{% block title %} {% endblock %}</title>
</head>
<body>

    {% load l10n %}
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">  
        <a class="navbar-brand" href="{% url 'bank_app:index' %}">Sketchy Bank</a>
        <ul class="navbar-nav">
            {% if user.is_staff %}
            <li><a class="nav-link" href="{% url 'bank_app:staff_new_customer' %}">New Customer</a></li>
            {% else %}
            <li><a class="nav-link" href="{% url 'bank_app:make_transfer' %}">Make Transfer</a></li>
            <li><a class="nav-link" href="{% url 'bank_app:make_loan' %}">Make Loan</a></li>
            {% endif %}
            {% if user.is_superuser %}
                <li><a class="nav-link" href="{% url 'admin:index' %}">Django Admin</a></li>
                {% endif %}
                <li><a class="nav-link" href="{% url 'logout' %}">Log out</a></li>
        </ul>
    </nav>
</header>
    
    
        

    <main>

     {% block main %}
     {% if user.is_staff %}
     <h2> Staff Portal </h2>
     {% else %}
     <h2> Customer Portal </h2>
     {% endif %}
     {% endblock main %}
     
    </main>

    <footer class="bg-light text-center">
        <p>&copy; 2021 Sketchy Bank</p>
    </footer>
    <script src="https://unpkg.com/htmx.org@1.5.0" integrity="sha384-oGA+prIp5Vchu6we2YkI51UtVzN9Jpx2Z7PnR1I78PnZlN8LkrCT4lqqqmDkyrvI" crossorigin="anonymous"></script>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>

</body>
</html>